### PR TITLE
Creates Roots.io Bedrock install

### PR DESCRIPTION
**Pull request by caseypatrickdriscoll**
Adds a --bedrock, -bed flag to install Roots.io Bedrock app install.

Should be straight forward. Very similar to wordpress-skeleton. In fact, logic in the same place.

Should also be non-interfering, very clean insert. Lemme know if need changes. Cheers!

### CODE REVIEW

**Comment by caseypatrickdriscoll** [comment]
Should mention, only tested on vanilla install. No multisite or any other options.

2015-07-09 at 11 41 pm

**Comment by bradp** [comment]
Looks good at first glance, I'll do some testing tomorrow / over the weekend, but should be good to merge.

**Comment by caseypatrickdriscoll** [comment]
:squeee:

**Comment by bradp** [comment]
Thanks for this! Merging it in now, and am planning on tagging a new version this weekend so this will go out to everyone.

Closes https://github.com/bradp/vv/issues/126

**Pull request merged**
