### PR TITLE
vv create: Add new site to vvv-config.yml to provision

### LINKED ISSUE #324: Unabled to Access New Site
It seems like its skipping a step where it should be installing database and htdocs etc. but its not. I tried so many times and it still doesn't work. is there a solution for this.

### PR DESCRIPTION
**Pull request by sdulaney**
Fixes #324, issue provisioning new site with vv create. Appends sites to the new YAML config file that controls VVV, explained by @LoreleiAurora in Varying-Vagrant-Vagrants/VVV#980.

### CODE REVIEW

**Comment by LoreleiAurora** [comment]
During this update the nginx config should probably be moved into the site dir and named vvv-config.conf as the new provisioner allows sites to be stored in git and they wouldnt be much use without the nginx config.

**Comment by sdulaney** [comment]
Good point thanks for the quick feedback @LoreleiAurora! Happy to work on this @bradp let me know.

**Comment by LoreleiAurora** [comment]
Also this just adds the line to the end of the file, as we add more options to the config file this will break as you cant guarantee the order of someones yaml file.

**Comment by jerome-toole** [comment]
When might this be merged in? I'd love to start using VV but I have the issue with failed provisioning -  #324

**Pull request merged**
