### PR TITLE
Adding *.domain support to subdomain networks

### PR DESCRIPTION
**Pull request by michaelryanmcneill**
Making VV handle wildcard subdomains as VVV does per #94.

### CODE REVIEW

**Comment by bradp** [comment]
Awesome, thanks!

**Comment by bradp** [comment]
I'll release a new version of VV this week, and this change will be in there.

**Comment by michaelryanmcneill** [comment]
Awesome, sounds good. Thanks @bradp.

**Comment by lvgunst** [comment]
Thanks for adding the wildcard alias!

**Pull request merged**
