### PR TITLE
# make terminal go to newly created sites home dir

### PR DESCRIPTION
**Pull request by thinkstylestudio**
I'm not sure if this is the right way to implement it or if this makes sense in terms of placement within the script but I thought it might be handy to be able to have the script automatically fire into the newly created directory in case one wanted to do more terminal commands etc. Thoughts? 

# make terminal go to newly created sites directory
	cd $path/www/$site

### CODE REVIEW

**Comment by bradp** [comment]
It's close to the right way to implement it. You'll want to also wrap the variables in double quotes, to escape any spaces and the like.

But the biggest issue with merging this in is that it won't actually do anything. Commands in bash are run in a sub-shell, so when you execute ``vv``, its happening outside of your terminal session basically. So, sadly, we can't plop the user anywhere but where they started.

There is this issue: https://github.com/bradp/vv/issues/67 which I am excited to build out, which will let a user run commands for a newly created site, but at the moment, we can't really take them to a new place in the terminal.

**Comment by thinkstylestudio** [comment]
Oh ok, that makes sense. I'm not a scripting guy, but your explanation made sense to me and helped thanks.

**Comment by bradp** [comment]
Of course! What you can do to test a potential PR locally, because you probably have `vv` installed normally, and don't want to overwrite it in a potentially breaking way, is cloning your copy locally, and then in the directory with the vv you're modifying, you can run it as `./vv`, and that will call the one in the directory, while `vv` will call the working copy.

I'd love to see some mroe PRs!

**Comment by thinkstylestudio** [comment]
Appreciate it. The script is REALLY handy and has become a staple way of spinning up and terminating installs..

**Pull request closed without merging**
